// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwmZnN9fyy9YLinHg0snJJfx02Qj2cWe4',
    appId: '1:260392275908:web:55c719e59fc670c6041e91',
    messagingSenderId: '260392275908',
    projectId: 'web-live-demo',
    authDomain: 'web-live-demo.firebaseapp.com',
    databaseURL: 'https://web-live-demo-default-rtdb.firebaseio.com',
    storageBucket: 'web-live-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDllxYFX22vUbENhRrCYcOS7R96wG_ScFg',
    appId: '1:260392275908:android:7389d889f5197081041e91',
    messagingSenderId: '260392275908',
    projectId: 'web-live-demo',
    databaseURL: 'https://web-live-demo-default-rtdb.firebaseio.com',
    storageBucket: 'web-live-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtzQNcyyaK2GVrxtubEV9Sz5UUNuL_maI',
    appId: '1:260392275908:ios:5e9c5b01c4515fe6041e91',
    messagingSenderId: '260392275908',
    projectId: 'web-live-demo',
    databaseURL: 'https://web-live-demo-default-rtdb.firebaseio.com',
    storageBucket: 'web-live-demo.appspot.com',
    iosBundleId: 'com.hiennv.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtzQNcyyaK2GVrxtubEV9Sz5UUNuL_maI',
    appId: '1:260392275908:ios:5e9c5b01c4515fe6041e91',
    messagingSenderId: '260392275908',
    projectId: 'web-live-demo',
    databaseURL: 'https://web-live-demo-default-rtdb.firebaseio.com',
    storageBucket: 'web-live-demo.appspot.com',
    iosBundleId: 'com.hiennv.testing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAbT1t7T1iN7wU7Go6HOYeC_iVqzZzoGc',
    appId: '1:260392275908:web:635e09046d9ea0ce041e91',
    messagingSenderId: '260392275908',
    projectId: 'web-live-demo',
    authDomain: 'web-live-demo.firebaseapp.com',
    databaseURL: 'https://web-live-demo-default-rtdb.firebaseio.com',
    storageBucket: 'web-live-demo.appspot.com',
  );
}
